In [1]:
import pandas as pd
path = "..\Dataset\API_Kaggle\weather_classification_data.csv"
df = pd.read_csv(path)
df

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,-1.0,76,3.5,23.0,cloudy,1067.23,1,Winter,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,overcast,984.27,0,Winter,2.0,inland,Snowy
13199,-5.0,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [2]:
to_drop = ['Season', 'Location']
df_drop = df.drop(columns=to_drop)
print(df_drop)

       Temperature  Humidity  Wind Speed  Precipitation (%)    Cloud Cover  \
0             14.0        73         9.5               82.0  partly cloudy
1             39.0        96         8.5               71.0  partly cloudy
2             30.0        64         7.0               16.0          clear
3             38.0        83         1.5               82.0          clear
4             27.0        74        17.0               66.0       overcast
...            ...       ...         ...                ...            ...
13195         10.0        74        14.5               71.0       overcast
13196         -1.0        76         3.5               23.0         cloudy
13197         30.0        77         5.5               28.0       overcast
13198          3.0        76        10.0               94.0       overcast
13199         -5.0        38         0.0               92.0       overcast

       Atmospheric Pressure  UV Index  Visibility (km) Weather Type
0                   1010.82         2              3.5        Rainy
1                   1011.43         7             10.0       Cloudy
2                   1018.72         5              5.5        Sunny
3                   1026.25         7              1.0        Sunny
4                    990.67         1              2.5        Rainy
...                     ...       ...              ...          ...
13195               1003.15         1              1.0        Rainy
13196               1067.23         1              6.0        Snowy
13197               1012.69         3              9.0       Cloudy
13198                984.27         0              2.0        Snowy
13199               1015.37         5             10.0        Rainy

[13200 rows x 9 columns]

In [3]:
# mengakses baris dengan label 5
# dan kolom dengan label Weather Type
df.loc[5, 'Weather Type']

'Cloudy'

In [4]:
# mengakses baris ke 6(mulai dari 0
# dan kolom ke 11(mulai dari 0)
df.iloc[5,10]

'Cloudy'

In [5]:
new_names = {'Precitipation (%)': 'Precipitation',
             'Visibility (km)': 'Visibility',}
df.rename(columns=new_names, inplace=True)
# perintah inplace = True akan menyimpan perubahan pada dataframe df
df

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility,Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,-1.0,76,3.5,23.0,cloudy,1067.23,1,Winter,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,overcast,984.27,0,Winter,2.0,inland,Snowy
13199,-5.0,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [6]:
# perintah isna() untuk mengecek NaN pada df
# perintah sum() untuk menjumlahkan jumlah NaN
df.isna().sum()

Temperature             0
Humidity                0
Wind Speed              0
Precipitation (%)       0
Cloud Cover             0
Atmospheric Pressure    0
UV Index                0
Season                  0
Visibility              0
Location                0
Weather Type            0
dtype: int64

In [7]:
import numpy as np

# membuat dataframe df_change baru yang berisi data dari dataframe df
df_new=df.copy()

# mengubah nilai "Winter pada kolom Season dengan nilai NaN
df_new["Season"] = df_new["Season"].replace("Winter", np.NaN)

# mengubah nilai negatif pada kolom Temperature dengan nilai NaN
df_new. Temperature=df_new. Temperature.mask(df_new.Temperature.lt(0),np.NaN)

df_new

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility,Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,NaN,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,NaN,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,NaN,76,3.5,23.0,cloudy,1067.23,1,NaN,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,overcast,984.27,0,NaN,2.0,inland,Snowy
13199,NaN,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [8]:
# perintah isna() untuk mengecek NaN pada df
# perintah sum() untuk menjumlahkan jumlah NaN
df_new.isna().sum()

Temperature             2337
Humidity                   0
Wind Speed                 0
Precipitation (%)          0
Cloud Cover                0
Atmospheric Pressure       0
UV Index                   0
Season                  5610
Visibility                 0
Location                   0
Weather Type               0
dtype: int64

In [9]:
# perintah dropna() menghapus sel yang kosong
df_drop_nan = df_new.dropna()
df_drop_nan

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility,Location,Weather Type
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
5,32.0,55,3.5,26.0,overcast,1010.03,2,Summer,5.0,inland,Cloudy
10,35.0,45,6.0,86.0,partly cloudy,879.88,2,Spring,1.0,mountain,Cloudy
...,...,...,...,...,...,...,...,...,...,...,...
13191,27.0,48,6.5,14.0,clear,1029.37,8,Summer,8.0,inland,Sunny
13192,31.0,24,8.0,5.0,clear,1029.61,8,Summer,9.0,inland,Sunny
13194,29.0,62,13.0,17.0,overcast,1002.81,2,Spring,5.0,coastal,Cloudy
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy

In [10]:
# perintah isna() untuk mengecek NaN pada df
# perintah sum() untuk menjumlahkan jumlah NaN
df_drop_nan.isna().sum()

Temperature             0
Humidity                0
Wind Speed              0
Precipitation (%)       0
Cloud Cover             0
Atmospheric Pressure    0
UV Index                0
Season                  0
Visibility              0
Location                0
Weather Type            0
dtype: int64

In [11]:
#perintah mode() menentukan nilai modus dari df
#penambahan [0] karena mode() mengembalikan nilai series
#walaupun hanya satu value
#sehingga perlu diset indeks ke-0 yang diambil
modus = df_new['Season'].mode() [0]
modus

'Spring'

In [12]:
# perintah fillna mengisi nilai modus ke seluruh nilai kosong dari df
df_new["Season"] = df_new["Season"].fillna(modus)
df_new

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility,Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Spring,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Spring,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,NaN,76,3.5,23.0,cloudy,1067.23,1,Spring,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,overcast,984.27,0,Spring,2.0,inland,Snowy
13199,NaN,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [13]:
# perintah isna() untuk mengecek NaN pada df
# perintah sum() untuk menjumlahkan jumlah NaN
df_new.isna().sum()

Temperature             2337
Humidity                   0
Wind Speed                 0
Precipitation (%)          0
Cloud Cover                0
Atmospheric Pressure       0
UV Index                   0
Season                     0
Visibility                 0
Location                   0
Weather Type               0
dtype: int64

In [14]:
!pip install feature-engine

Collecting feature-engine
  Downloading feature_engine-1.9.3-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.18.2 in c:\users\santo\anaconda3\envs\dip\lib\site-packages (from feature-engine) (1.26.4)
Requirement already satisfied: pandas>=2.2.0 in c:\users\santo\anaconda3\envs\dip\lib\site-packages (from feature-engine) (2.2.2)
Requirement already satisfied: scikit-learn>=1.4.0 in c:\users\santo\anaconda3\envs\dip\lib\site-packages (from feature-engine) (1.6.1)
Requirement already satisfied: scipy>=1.4.1 in c:\users\santo\anaconda3\envs\dip\lib\site-packages (from feature-engine) (1.15.1)
Collecting statsmodels>=0.11.1 (from feature-engine)
  Downloading statsmodels-0.14.5-cp310-cp310-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\santo\anaconda3\envs\dip\lib\site-packages (from pandas>=2.2.0->feature-engine) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\santo\anaconda3\envs\dip\lib\site-packages (from pandas>=2.2.0->feature-engine) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\santo\anaconda3\envs\dip\lib\site-packages (from pandas>=2.2.0->feature-engine) (2025.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\santo\appdata\roaming\python\python310\site-packages (from scikit-learn>=1.4.0->feature-engine) (1.5.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\santo\anaconda3\envs\dip\lib\site-packages (from scikit-learn>=1.4.0->feature-engine) (3.6.0)
Collecting patsy>=0.5.6 (from statsmodels>=0.11.1->feature-engine)
  Downloading patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: packaging>=21.3 in c:\users\santo\anaconda3\envs\dip\lib\site-packages (from statsmodels>=0.11.1->feature-engine) (24.2)
Requirement already satisfied: six>=1.5 in c:\users\santo\anaconda3\envs\dip\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->feature-engine) (1.17.0)
Downloading feature_engine-1.9.3-py3-none-any.whl (229 kB)
Downloading statsmodels-0.14.5-cp310-cp310-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB 11.8 MB/s eta 0:00:01
   ------------------ --------------------- 4.5/9.6 MB 11.7 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.6 MB 11.8 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 11.6 MB/s eta 0:00:00
Downloading patsy-1.0.1-py2.py3-none-any.whl (232 kB)
Installing collected packages: patsy, statsmodels, feature-engine
Successfully installed feature-engine-1.9.3 patsy-1.0.1 statsmodels-0.14.5

In [15]:
#perintah mean() untuk mencari rata-rata dari data
#perintah fillna untuk mengganti missing value dengan mean
df_mean = df_new.copy()
df_mean["Temperature"] = df_mean["Temperature"].fillna(value=df_mean["Temperature"].mean())
df_mean

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility,Location,Weather Type
0,14.000000,73,9.5,82.0,partly cloudy,1010.82,2,Spring,3.5,inland,Rainy
1,39.000000,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.000000,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.000000,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.000000,74,17.0,66.0,overcast,990.67,1,Spring,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.000000,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,24.678266,76,3.5,23.0,cloudy,1067.23,1,Spring,6.0,coastal,Snowy
13197,30.000000,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.000000,76,10.0,94.0,overcast,984.27,0,Spring,2.0,inland,Snowy
13199,24.678266,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [16]:
#Mengatasi nilai missing value dengan imputasi suka-suka
#Nilai suka-suka yang diberikan pada contoh adalah 99
df_arbitrary = df_new.copy()
df_arbitrary["Temperature"] = df_arbitrary["Temperature"].fillna(value=99)
df_arbitrary

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility,Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Spring,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Spring,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,99.0,76,3.5,23.0,cloudy,1067.23,1,Spring,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,overcast,984.27,0,Spring,2.0,inland,Snowy
13199,99.0,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [24]:
#Import EndTailImputer
from feature_engine.imputation import EndTailImputer

#Membuat imputer
#metode imputasi = gaussian
#tail = right -- > limit = mean + 3*std
imputer = EndTailImputer(imputation_method='gaussian', tail='right')

df_endTail = df_new.copy()

#Melakukan proses learning data untuk menentukan nilai yang hilang
imputer.fit(df_endTail)

#Mengimputasi data yang hilang
test_t = imputer.transform(df_endTail)

#Tampilkan data
test_t

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility,Location,Weather Type
0,14.00000,73,9.5,82.0,partly cloudy,1010.82,2,Spring,3.5,inland,Rainy
1,39.00000,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.00000,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.00000,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.00000,74,17.0,66.0,overcast,990.67,1,Spring,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.00000,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,-16.57864,76,3.5,23.0,cloudy,1067.23,1,Spring,6.0,coastal,Snowy
13197,30.00000,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.00000,76,10.0,94.0,overcast,984.27,0,Spring,2.0,inland,Snowy
13199,-16.57864,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [18]:
#Import randomsample imputer
from feature_engine. imputation import RandomSampleImputer

df_randomImputer = df_new.copy()

#Buat imputernya
imputer = RandomSampleImputer()

#Fit imputer ke dataframe
imputer.fit(df_randomImputer)

#Mengimputasi data yang hilang
test_t = imputer. transform(df_randomImputer)
test_t

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility,Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Spring,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Spring,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,2.0,76,3.5,23.0,cloudy,1067.23,1,Spring,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,overcast,984.27,0,Spring,2.0,inland,Snowy
13199,37.0,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [ ]:
from sklearn.preprocessing import Normalizer

data = df_mean.iloc[:,[0,5,6]]

#Buat objek skalar dengan normalizer
max_abs = Normalizer(norm = 'l2')

#Sesuaikan scaler dengan data
max_abs.fit(data)

#Mengubah data
train_scaled = max_abs.transform(data)

#Tampilkan hasil
df_normal=pd.DataFrame(train_scaled, columns=["Temperature", "Atmospheric Pressure", "UV Index"])
df_normal

       Temperature  Atmospheric Pressure  UV Index
1245      0.000000              1.000000  0.000000
10424     0.000000              0.999999  0.001004
1634      0.000000              0.999999  0.001013
7150      0.000000              1.000000  0.000000
8930      0.000000              0.999987  0.005010
...            ...                   ...       ...
9328      0.100267              0.994961  0.000000
2958      0.103860              0.994584  0.003883
8353      0.104832              0.994432  0.010777
10993     0.105187              0.994429  0.006818
5085      0.106992              0.994178  0.012760

[13200 rows x 3 columns]

In [23]:
from sklearn.preprocessing import MinMaxScaler

#Memilih kolom
data = df_mean.iloc[:, [0,5,6]]

#Buat objek skalar
scaler = MinMaxScaler()

#Sesuaikan scaler dengan data dan
#mengubah data
train_scaled = scaler.fit_transform(data)

#Tampilkan hasil
df_normal=pd.DataFrame(train_scaled, columns=["Temperature", "Atmospheric Pressure", "UV Index"])
df_normal

       Temperature  Atmospheric Pressure  UV Index
0         0.128440              0.527951  0.142857
1         0.357798              0.529480  0.500000
2         0.275229              0.547746  0.357143
3         0.348624              0.566614  0.500000
4         0.247706              0.477461  0.071429
...            ...                   ...       ...
13195     0.091743              0.508732  0.071429
13196     0.226406              0.669298  0.071429
13197     0.275229              0.532637  0.214286
13198     0.027523              0.461425  0.000000
13199     0.226406              0.539352  0.357143

[13200 rows x 3 columns]

In [30]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

#Memilih kolom
data = df_mean.iloc[:, [0,5,6]]

#Buat objek skalar
scaler = StandardScaler()

#Sesuaikan scaler dengan data dan
scaler.fit(data)
#mengubah data
train_scaled = scaler.transform(data)

#Tampilkan hasil
df_normal=pd.DataFrame(train_scaled, columns=["Temperature", "Atmospheric Pressure", "UV Index"])
df_normal_sorted = df_normal.sort_values(by="Temperature")
df_normal_sorted

       Temperature  Atmospheric Pressure  UV Index
747      -1.978205             -0.273882 -0.779410
140      -1.978205             -0.301302 -1.038715
7900     -1.978205             -0.428459 -0.779410
2459     -1.978205             -0.497280 -1.038715
7905     -1.978205             -0.650244 -1.038715
...            ...                   ...       ...
9328      6.198095              0.170226 -1.038715
8353      6.598894              0.246574  1.813646
2958      6.598894              0.505995 -0.001493
10993     6.679054              0.408410  0.776424
5085      6.759214              0.188507  2.332257

[13200 rows x 3 columns]